/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class usb_command_t implements lcm.lcm.LCMEncodable
{
    public float chip1_cmd[];
    public int chip1_flg[];
    public float chip2_cmd[];
    public int chip2_flg[];
    public float chip3_cmd[];
    public int chip3_flg[];
 
    public usb_command_t()
    {
        chip1_cmd = new float[30];
        chip1_flg = new int[1];
        chip2_cmd = new float[30];
        chip2_flg = new int[1];
        chip3_cmd = new float[30];
        chip3_flg = new int[1];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4b0674318281283eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.usb_command_t.class))
            return 0L;
 
        classes.add(lcmtypes.usb_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.chip1_cmd[a]); 
        }
 
        for (int a = 0; a < 1; a++) {
            outs.writeInt(this.chip1_flg[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.chip2_cmd[a]); 
        }
 
        for (int a = 0; a < 1; a++) {
            outs.writeInt(this.chip2_flg[a]); 
        }
 
        for (int a = 0; a < 30; a++) {
            outs.writeFloat(this.chip3_cmd[a]); 
        }
 
        for (int a = 0; a < 1; a++) {
            outs.writeInt(this.chip3_flg[a]); 
        }
 
    }
 
    public usb_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public usb_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.usb_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.usb_command_t o = new lcmtypes.usb_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.chip1_cmd = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.chip1_cmd[a] = ins.readFloat();
        }
 
        this.chip1_flg = new int[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.chip1_flg[a] = ins.readInt();
        }
 
        this.chip2_cmd = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.chip2_cmd[a] = ins.readFloat();
        }
 
        this.chip2_flg = new int[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.chip2_flg[a] = ins.readInt();
        }
 
        this.chip3_cmd = new float[(int) 30];
        for (int a = 0; a < 30; a++) {
            this.chip3_cmd[a] = ins.readFloat();
        }
 
        this.chip3_flg = new int[(int) 1];
        for (int a = 0; a < 1; a++) {
            this.chip3_flg[a] = ins.readInt();
        }
 
    }
 
    public lcmtypes.usb_command_t copy()
    {
        lcmtypes.usb_command_t outobj = new lcmtypes.usb_command_t();
        outobj.chip1_cmd = new float[(int) 30];
        System.arraycopy(this.chip1_cmd, 0, outobj.chip1_cmd, 0, 30); 
        outobj.chip1_flg = new int[(int) 1];
        System.arraycopy(this.chip1_flg, 0, outobj.chip1_flg, 0, 1); 
        outobj.chip2_cmd = new float[(int) 30];
        System.arraycopy(this.chip2_cmd, 0, outobj.chip2_cmd, 0, 30); 
        outobj.chip2_flg = new int[(int) 1];
        System.arraycopy(this.chip2_flg, 0, outobj.chip2_flg, 0, 1); 
        outobj.chip3_cmd = new float[(int) 30];
        System.arraycopy(this.chip3_cmd, 0, outobj.chip3_cmd, 0, 30); 
        outobj.chip3_flg = new int[(int) 1];
        System.arraycopy(this.chip3_flg, 0, outobj.chip3_flg, 0, 1); 
        return outobj;
    }
 
}

