"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class usb_command_t(object):
    __slots__ = ["chip1_cmd", "chip1_flg", "chip2_cmd", "chip2_flg", "chip3_cmd", "chip3_flg"]

    __typenames__ = ["float", "int32_t", "float", "int32_t", "float", "int32_t"]

    __dimensions__ = [[30], [1], [30], [1], [30], [1]]

    def __init__(self):
        self.chip1_cmd = [ 0.0 for dim0 in range(30) ]
        self.chip1_flg = [ 0 for dim0 in range(1) ]
        self.chip2_cmd = [ 0.0 for dim0 in range(30) ]
        self.chip2_flg = [ 0 for dim0 in range(1) ]
        self.chip3_cmd = [ 0.0 for dim0 in range(30) ]
        self.chip3_flg = [ 0 for dim0 in range(1) ]

    def encode(self):
        buf = BytesIO()
        buf.write(usb_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>30f', *self.chip1_cmd[:30]))
        buf.write(struct.pack('>1i', *self.chip1_flg[:1]))
        buf.write(struct.pack('>30f', *self.chip2_cmd[:30]))
        buf.write(struct.pack('>1i', *self.chip2_flg[:1]))
        buf.write(struct.pack('>30f', *self.chip3_cmd[:30]))
        buf.write(struct.pack('>1i', *self.chip3_flg[:1]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != usb_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return usb_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = usb_command_t()
        self.chip1_cmd = struct.unpack('>30f', buf.read(120))
        self.chip1_flg = struct.unpack('>1i', buf.read(4))
        self.chip2_cmd = struct.unpack('>30f', buf.read(120))
        self.chip2_flg = struct.unpack('>1i', buf.read(4))
        self.chip3_cmd = struct.unpack('>30f', buf.read(120))
        self.chip3_flg = struct.unpack('>1i', buf.read(4))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if usb_command_t in parents: return 0
        tmphash = (0x4b0674318281283e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if usb_command_t._packed_fingerprint is None:
            usb_command_t._packed_fingerprint = struct.pack(">Q", usb_command_t._get_hash_recursive([]))
        return usb_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", usb_command_t._get_packed_fingerprint())[0]

